// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: "2024-11-01",
  devtools: { enabled: true },
  modules: [
    "@nuxtjs/tailwindcss",
    "@vesp/nuxt-fontawesome",
    "@nuxt/image",
    "@nuxtjs/sitemap",
  ],
  sitemap: {
    siteUrl: "https://horecaflow-promote.techybear.eu",
  },
  fontawesome: {
    icons: {
      solid: [
        "bars",
        "times",
        "glass-martini-alt",
        "envelope",
        "phone",
        "clock",
        "chevron-right",
        "cash-register",
        "chart-line",
        "box",
        "users",
        "receipt",
        "mobile-alt",
        "glass-cheers",
        "table",
        "credit-card",
        "check",
        "shield-alt",
        "sync",
        "graduation-cap",
        "headset",
        "rocket",
        "star",
        "bolt",
        "expand-arrows-alt",
        "book",
        "question-circle",
        "envelope-open-text",
        "chevron-up",
        "chevron-down",
        "lightbulb",
        "gift",
        "heart",
        "comments",
        "calendar-alt",
      ],
      brands: ["linkedin", "twitter", "facebook", "instagram"],
    },
  },
  app: {
    head: {
      title: "HorecaFlow - Solution POS pour Bars et Restaurants",
      meta: [
        { charset: "utf-8" },
        { name: "viewport", content: "width=device-width, initial-scale=1" },
      ],
      link: [{ rel: "icon", type: "image/x-icon", href: "/favicon.ico" }],
    },
  },
});
